language: python
python:
- '3.5'
- '3.6'
# notifications:
#   email:
#     on_success: change
#     on_failure: always
before_install:
  - pip install codecov
  # required for the pip only-binary fkag
  - pip install --upgrade pip setuptools wheel
  # we don't want to compile sources for the following packages:
  - pip install --only-binary=numpy numpy
install:
  - pip install ".[test]"
script: pytest --cov=ssdts_matching
after_success:
  - codecov
